#!/bin/bash
workspace(){
    CW=$(echo 'local awful = require("awful"); return awful.tag.selected(1).name' | awesome-client | awk -F'[^0-9]*' '{print $2}')
    
    O1=$(wmctrl -l | grep -v "Eww - bar" | awk '$2 ~ /0/ {print "occupied_1"; exit}')
    O2=$(wmctrl -l | grep -v "Eww - bar" | awk '$2 ~ /1/ {print "occupied_2"; exit}')
    O3=$(wmctrl -l | grep -v "Eww - bar" | awk '$2 ~ /2/ {print "occupied_3"; exit}')
    O4=$(wmctrl -l | grep -v "Eww - bar" | awk '$2 ~ /3/ {print "occupied_4"; exit}')

    echo "(box :class 'workspaces active_workspace_$CW $O1 $O2 $O3 $O4' :orientation 'v' :space-evenly 'false' :valign 'start' :spacing 7(button :class 'workspace_1' :onclick 'echo \"screen[1].tags[1]:view_only()\" | awesome-client' '')(button :class 'workspace_2' :onclick 'echo \"screen[1].tags[2]:view_only()\" | awesome-client' '')(button :class 'workspace_3' :onclick 'echo \"screen[1].tags[3]:view_only()\" | awesome-client' '󰎈')(button :class 'workspace_4' :onclick 'echo \"screen[1].tags[4]:view_only()\" | awesome-client' ''))"
}

xprop -spy -root _NET_CURRENT_DESKTOP | while read -r; do
    workspace
done
