#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.bar"
CFG="$HOME/.config/eww/bar"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open bar
}

close_eww() {
	${EWW} --config "$CFG" close bar
	rm "$FILE"
}
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	close_eww
	touch "$FILE"
	run_eww
fi
	
