#!/bin/bash

get_icon(){
	if [[ ${VAL} -ge 67 ]]; then
		echo 󰕾
	elif [[ ${VAL} -ge 34 ]]; then
		echo 󰖀
	elif [[ ${VAL} -ge 1 ]]; then
		echo 󰕿
	else
		echo 󰝟
	fi
}

VAL=$(amixer sget Master | awk -F'[][]' '/Right:|Mono:/ && NF > 1 {sub(/%/, ""); printf "%0.0f\n", $2}')
if [[ "$1" == "--val" ]]; then
	echo $VAL
elif [[ "$1" == "--icon" ]]; then
	get_icon
fi
