#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.blight"
CFG="$HOME/.config/eww/popups/blight"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	CHECK="`cat $FILE`"
	if (($CHECK <= 0)); then
		${EWW} --config "$CFG" open blight
	fi
	sleep 2
	CHECK="`cat $FILE`"
	if (($CHECK <= 0)); then
		close_eww
	else
		$(echo $((CHECK - 1)) > $FILE)
	fi
		
}

close_eww() {
	${EWW} --config "$CFG" close blight
	rm "$FILE"
}
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	$(echo 0 > $FILE)
	run_eww
else
	CHECK="`cat $FILE`"
	$(echo $((CHECK + 1)) > $FILE)
	##sleep .5
	run_eww
fi
	
