#!/bin/python

import imaplib
obj = imaplib.IMAP4_SSL('imap.gmail.com',993)
obj.login('ricardo.m.o.morais@gmail.com','xwbx odpu elhb kctz')
obj.select()
print(len(obj.search(None, 'UnSeen')[1][0].split()))
