#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system calendar time fetch directories weather music power mail apps
	rm -rf "$FILE"
}

if [[ "$1" == "--dl" ]]; then
	close_dash && thunar ~/downloads &

elif [[ "$1" == "--docs" ]]; then
	close_dash && thunar ~/documents &

elif [[ "$1" == "--music" ]]; then
	close_dash && thunar ~/music &

elif [[ "$1" == "--pics" ]]; then
	close_dash && thunar ~/pictures &

elif [[ "$1" == "--cfg" ]]; then
	close_dash && thunar ~/.config &

elif [[ "$1" == "--local" ]]; then
	close_dash && thunar ~/.local/share &
fi
