#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`
cmd="firefox --new-tab"

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system calendar time fetch directories weather music power mail apps
	rm -rf "$FILE"
}

if [[ "$1" == "--ff" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--sn" ]]; then
	close_dash && signal-desktop &

elif [[ "$1" == "--dc" ]]; then
	close_dash && discord &

elif [[ "$1" == "--si" ]]; then
	close_dash && spotify-launcher &

elif [[ "$1" == "--gh" ]]; then
	close_dash && ${cmd} "https://github.com" &

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--lt" ]]; then
	close_dash && lutris &

elif [[ "$1" == "--mail" ]]; then
	close_dash && ${cmd} "https://gmail.com" &
fi
